### ISSUE TITLE
don't show moz-extension://... in the addressbar

### ISSUE THREAD

**Issue by 532910** [M-Reimer/android-pdf-js#1]
Is it possible to show the url directly, as desktop firefox does, without moz-extension://...?

**Comment by M-Reimer** [comment]
At least in theory this would be possible by using the filter mechanism offered by Mozilla.
I've tried that and I immediately ran into several bugs in the WebExtensions API.
That's a problem with Mozilla and it always was even before WebExtensions. To write good Firefox Addons you have to have some ability to find good workarounds as the APIs are often full of bugs and currently it also seems like Mozilla doesn't have too much priority into fixing WebExtensions bugs.
I'm particularly affected by this one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1543018
I have a "somewhat OK" workaround for this bug which works with my current way of doing things. If I use the filter, then I run into several caching issues again.

So here functionality wins over visual effect.

**Comment by M-Reimer** [comment]
Added label "upstream bug" even if this is not directly fixable by upstream.
I could implement this right away and I even did some tests.
Problem is that I will run into the "caching nightmare" again with the filter mechanism and content rewrite.

**Comment by M-Reimer** [comment]
Seems like there is some movement in the upstream bug.
Firefox 74 may have a fix for this but I still have to verify that a version without workaround really works there without any issues.
If so we just have to wait for Firefox 74 to land on Android.

**Comment by M-Reimer** [comment]
Added with my latest commits. I really hope this does not trigger any silly Web-Extension bugs, again, ...
