### ISSUE TITLE
Pinch to zoom results in blurry text

### ISSUE THREAD

**Issue by yoasif** [M-Reimer/android-pdf-js#10]
Steps to reproduce:

1. Navigate to https://www.irs.gov/pub/irs-pdf/f1040.pdf
2. Pinch to zoom into text

What happens:

Text is blurry and not smooth.

![signal-2020-09-30-170842](https://user-images.githubusercontent.com/152493/94739867-a1f5de00-033f-11eb-8f20-b48c5a8ab366.png)

Expected result:

Non-blurry text.

**Comment by M-Reimer** [comment]
If you try the same on a desktop Firefox (also has PDF.js built in) you'll see that this also happens there.
The goal of my Add-on is to integrate a (mostly) unchanged PDF.js into Firefox for Android and (soon) "Fenix Nightly". I'm no PDF.js developer and don't understand their code to a level that would allow me to fix things there.

But maybe you want to post this Issue in the PDF.js Issue tracker for them to review.

**Comment by yoasif** [comment]
@M-Reimer That isn't true - if you use Firefox Nightly on desktop with pinch to zoom enabled, text may be blurry while zooming, but as soon as you stop the zoom action, the text is rendered to be sharp. Please try this on a apz enabled desktop browser.

**Comment by M-Reimer** [comment]
The "pinch to zoom" hack, that I use, controls the PDF.js internal zoom.

Or to verify that it is a PDF.js bug: Zoom in with the "+" button in the toolbar. You'll see that the text gets blurry, too --> PDF.js issue.
