### ISSUE TITLE
Update PDF.js to v2.7.570

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [M-Reimer/android-pdf-js#12]
This release become stable now

**Comment by M-Reimer** [comment]
I guess I should add a note to somewhere that I don't want to be notified about each new release of PDF.js via Issue :laughing: 

I had a release just a few days ago, so I will not create a new release directly just to ship a new PDF.js version. Usually the changes are that small that noone sees big differences anyway.

**Comment by M-Reimer** [comment]
A new release is on its way.
