### ISSUE TITLE
Viewer lost the title

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [M-Reimer/android-pdf-js#13]
Normally PDF.js Viewer usually display the title, and you can see it by pressing the lock icon. However this is missing in your extension.

Fig 1. Open Mozillaʼs demo
![Screenshot_20210429-183916](https://user-images.githubusercontent.com/10364351/116539420-5dedaa80-a91b-11eb-90a6-32fad397da9e.png)
Fig 2. Open sample file from the same site
![Screenshot_20210429-183937](https://user-images.githubusercontent.com/10364351/116539516-7f4e9680-a91b-11eb-8641-98e25eaac9d7.png)

**Comment by M-Reimer** [comment]
I know why this happens, but I have to solve a much more serious problem, first.

At least for me, with the Add-on installed, the first page loaded in Firefox always fails to load. Until the reason for this is found, I won't do any other fixes.

**Comment by M-Reimer** [comment]
Should be fixed in the upcoming release.
