### ISSUE TITLE
Cannot add the extension in my own AMO collection

### ISSUE THREAD

**Issue by ImGittyKat** [M-Reimer/android-pdf-js#14]
I love this addon's idea, but I wasn't able to include it in my own collection. It just doesn't show up on the search list.

![AMO-search](https://user-images.githubusercontent.com/83912975/117579015-98580400-b0e0-11eb-96f6-78a58bf17c9c.png)

Could this be perhaps because of the "_This add-on is not available on your platform._" prompt on PC?

I really need it in **my own** collection as I include there every useful addon that is compatible with Nightly for Android (this collection is also used by my friends and other people that I recommend firefox to)

**Comment by KrasnayaPloshchad** [comment]
I think this issue should be reported at https://github.com/mozilla/addons-frontend to let them know.

**Comment by M-Reimer** [comment]
There is a link on this GitHub main page (README.md):
https://addons.mozilla.org/en-US/android/addon/android-pdf-js/
If you use this, you can't install the Add-on, but you can add it to your collection.
