### ISSUE TITLE
Download button doesn't work

### ISSUE THREAD

**Issue by Rodze** [M-Reimer/android-pdf-js#15]
When a pdf is opened in the viewer, the download button does nothing. It should open the option to "download" (save) the pdf like it does in the desktop version. Android 9 on Galaxy S9 with Nightly 90 build 2015812107

Is it broken just on my phone?

**Comment by mobd** [comment]
I have the same issue on Android 10 with nightly 91.0a1 build #2015815371.

**Comment by M-Reimer** [comment]
I can reproduce this and I hope updating PDF.js is all that is needed. Will try this as soon as possible.

**Comment by M-Reimer** [comment]
Actually it was more than just the version. It seems like using an iframe to host the viewer causes some security checks to fail which blocks the PDF save.
I had to rework how I load the viewer and now it seems to work.
A new release is on its way.
