### ISSUE TITLE
Support embedded PDF

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [M-Reimer/android-pdf-js#17]
PDFObject website have some examples to require load PDF file within webpage. However these examples failed to display the PDF files even if your extension is installed, but rather showing “This browser does not support inline PDFs” notice. These examples including:
* Invoking conditional JavaScript upon successful embed
* Detection of PDF support
* Embed two PDFs on one HTML page
* Full-browser embed (no selector specified)
* Full-browser embed (explicit selector) with PDF Open * * * Params specified
* Full-browser embed (explicit selector)

It would be nice if your extension could allow to build a viewer in these pages to load PDF.
See: https://pdfobject.com/#examples

> 91.0a1 (Build #2015818539)
> AC: 91.0.20210625143048, 6dc0ca5c14
> GV: 91.0a1-20210625093436
> AS: 79.0.0

**Comment by M-Reimer** [comment]
Should be possible but I'm still trying to workaround another issue.

**Comment by M-Reimer** [comment]
Now tracked here: https://github.com/pipwerks/PDFObject/issues/250

**Comment by M-Reimer** [comment]
Embedding works if you don't use PDFObject. Just follow some tutorial like this one:

https://www.w3docs.com/snippets/html/how-to-embed-pdf-in-html.html

**Comment by KrasnayaPloshchad** [comment]
Oh I see.
