### ISSUE TITLE
pdf viewer window size

### ISSUE THREAD

**Issue by eddiechen** [M-Reimer/android-pdf-js#19]
Thank you for creating this. This is exactly what I've been looking for to solve my project. One quick question, is there any way to increase the window size of the pdf viewer?

**Comment by M-Reimer** [comment]
What is exactly your problem? What I'm offering here is an Add-on to open PDF files from the web directly into Firefox on Android. And there it will open in full screen.

**Comment by eddiechen** [comment]
I am testing this on my samsung Galaxy tab A7. It is working perfectly, but the pdf viewer window is a bit small. I was wondering if I could increase the size of the window to see more of the pdf.

**Comment by M-Reimer** [comment]
I can not test on tablets. Can you please attach a screenshot to show the problem?

**Comment by M-Reimer** [comment]
Without additional feedback I have to close this one. If you find the time to post a screenshot, I'll reopen the Issue.
