### ISSUE TITLE
canvas very low resolution on Mull (Firefox for Android)

### ISSUE THREAD

**Issue by PaulGrandperrin** [M-Reimer/android-pdf-js#23]
This is the same PDF opened in Mull vs Android's native PDF viewer : 
![Screenshot_20220828-132719](https://user-images.githubusercontent.com/1748936/187072021-e850f274-e6ab-4c51-a785-649d9ebd0d35.png)
![Screenshot_20220828-132659](https://user-images.githubusercontent.com/1748936/187072024-94c9369c-005f-41fb-87ab-a327ed8aa980.png)

Thanks for this addon!

**Comment by M-Reimer** [comment]
It is very likely that you are wrong here as this might be a PDF.js issue.

Can you post the full URL to the PDF?

**Comment by PaulGrandperrin** [comment]
> It is very likely that you are wrong here as this might be a PDF.js issue.

Oh, yes, I actually have no idea if that's the canvas or something else.

It's just very blurry, but I didn't try investigating with developer tools.

> 
> Can you post the full URL to the PDF?

https://www.insee.fr/fr/statistiques/fichier/2586032/LOGFRA17o1_F10.1.pdf

**Comment by PaulGrandperrin** [comment]
Hum, i have the same issue when using pdf.js directly, on their example pdf: https://mozilla.github.io/pdf.js/web/viewer.html
![Screenshot_20220828-164301.png](https://user-images.githubusercontent.com/1748936/187079890-854f03ad-1426-4e1a-98b3-5507c8266be4.png)

**Comment by PaulGrandperrin** [comment]
Ok, so https://mozilla.github.io/pdf.js/web/viewer.html works well on the official Firefox for Android ( stable and nightly), so it's very probably an issue with Mull.

Sorry for wrong report, i guess we can close this issue.

**Comment by PaulGrandperrin** [comment]
The solution was to set `privacy.resistFingerprinting` to false
