### ISSUE TITLE
How do I add your addon to my collection?

### ISSUE THREAD

**Issue by phs** [M-Reimer/android-pdf-js#25]
Before you close as "read that fun manual", hear me out.

I have created an account, an add-on collection and added a few other add-ons to it.  I'd love to add yours.  However the search bar at the top appears to absolutely refuse to produce your add-on as a result, regardless of query.

Why is that?

Either way, by changing the browser's custom add-on collection to yours, I can then install your add-on, and then switch the custom collection back to mine.  Your add-on itself incidentally seems to work perfectly, and thankfully the browser didn't disable it or whatever when I switched back.

It doesn't seem like it should matter, but I'm using Firefox for Android beta (which now supports custom add-on collections), rather than nightly.

**Comment by M-Reimer** [comment]
The addon is for Android only. So it is impossible to find it on desktop Firefox.

On my README.md is a direct link you can follow.

**Comment by phs** [comment]
In my first attempt I was using Firefox Desktop, and indeed I couldn't even see your add-on's details page without a direct link, as you say.  However I am talking about something else.

> The addon is for Android only. So it is impossible to find it on desktop Firefox.

Are you saying that the browser I use to view the addons collection edit page determines what results I see?

I'm talking about the search box with default content "Find an add-on to include in this collection" on https://addons.mozilla.org/en-US/firefox/collections/xxx/xxx/edit/?page=1&collection_sort=-added (substitute account and collection name as appropriate.)  Not the general "Find add-ons" search box in the site header.

Just now I logged into the add-ons site and went to the edit page in Firefox for Android on my device.  There the edit collection search box also shows no results.

**Comment by M-Reimer** [comment]
The whole addon situation on Android is intentionally crippled by Mozilla. You only find Addons Mozilla decides to be "good".

You have to directly follow my link on desktop. Directly on the addon page you find a section to add this specific addon to a collection.

**Comment by phs** [comment]
> The whole addon situation on Android is intentionally crippled by Mozilla. You only find Addons Mozilla decides to be "good".

I was picking up on that, yea.

> You have to directly follow my link on desktop. Directly on the addon page you find a section to add this specific addon to a collection.

That works, thank you.

For posterity, here are the exact steps I needed.  This first set were covered by the tutorial linked in the add-on README
* Create an addons.mozilla.org account
* Create a custom add-on collection
* Use a supported version of Firefox for Android and enable the custom add-on collection

The remaining steps I needed were not covered by the tutorial
* Do not use the search field on the custom add-on collection search page.
* While logged into addons.mozilla.org, go to the add-on directly using the link (so https://addons.mozilla.org/en-US/android/addon/android-pdf-js/ )
* Find the "Add to collection" section on the bottom left of the page, and use the drop-down.

Those last steps might go in the README as well.  Either way, thank you for your patience.
