### ISSUE TITLE
Showing PDFs behind session-based authentication doesn't work.

### ISSUE THREAD

**Issue by orwell96** [M-Reimer/android-pdf-js#3]
Hi,

I really appreciate this add-on, as i've become really annoyed of PDFs cluttering my Downloads folder

I often deal with documents that are protected with some sort of authentication, which makes it necessary that I open (and download) PDFs from within firefox and not using 3rd party apps such as Google Drive PDF viewer.

However, when I try to access a document that is only accessible while logged into a certain website, the addon doesn't seem to send along the session cookies, which causes the document to be not found (or be invalid because the page sends some other "unauthenticated" HTML page). Hitting the download button afterwards works perfectly fine and downloads the file.

Note that this doesn't affect simple HTTP authentication, only session-based authentication.

**Comment by M-Reimer** [comment]
I think I'll have to create a test case for this first as I have no such service in use. But I'll try to reproduce this somehow.

**Comment by M-Reimer** [comment]
I have tried to find a possible reason for this problem.
My guess was that cookies aren't sent when the PDF is fetched.
But this is not the case unfortunately. Seems like cookies are sent by PDF.js.

So without a simple testcase (maybe some free publicly available service) I won't be able to fix this.

**Comment by orwell96** [comment]
I've set up a simple test case for you.
http://www.bleipb.de/pdfcookie/

setcookie.php sets a cookie
clearcookie.php clears it
cookiestate.php shows whether the cookie is ok
serve.php serves the pdf file grundintegrale.pdf if the cookie is ok, or returns a 403 if the cookie is not ok.

**Comment by M-Reimer** [comment]
Thank you.
I'll have a closer look at this as soon as possible.

**Comment by M-Reimer** [comment]
OK. Still took a while to reproduce but now I at least know why it doesn't work for you.

To make it work right away, all you have to do is to enable "third party cookies". Should be under "Privacy" -> "Cookies".

The reason is simple: As the PDF reader is served by my Addon, accessing the PDF file is "third party" access.

I can think of some workarounds but mostly hacks which need serious consideration to not open any security holes.

**Comment by orwell96** [comment]
Right, this fixes the issue. Thank you for investigating.

**Comment by M-Reimer** [comment]
But IMHO this isn't the fix that should be in there. It should not be required to allow third party cookies for Addons to work the way they should. I can work around this. I already have some code in place to pass the "Referer" header over to the request made by PDF.js and I could also pass the "Cookies" header the same way. It would just need some more security checks to make this secure.

But before hacking around, I prefer to try to "delegate" this to "upstream" first:
https://bugzilla.mozilla.org/show_bug.cgi?id=1608685

**Comment by M-Reimer** [comment]
May be fixed together with #1 but this would require some creative remapping of PDF.js files so we can trick PDF.js to run actually in the context of the original domain. If I manage to do this the PDF access would no longer be 3rd party.

**Comment by Poopooracoocoo** [comment]
looks like this has been fixed :3

must be because https://bugzilla.mozilla.org/show_bug.cgi?id=1629436 "network.cookie.sameSite.laxByDefault breaks my add-on" was fixed

**Comment by M-Reimer** [comment]
There is a good chance that this is fixed now as I'm loading the PDF in context of its original URL so we no longer have a "same origin" problem here.
New release is on its way.
