### ISSUE TITLE
Fenix support

### ISSUE THREAD

**Issue by 532910** [M-Reimer/android-pdf-js#6]
WebExtension Support has been added to Fenix

Looks like android-pdf-js should be adopted a bit.

https://github.com/mozilla-mobile/fenix/issues/5315

**Comment by M-Reimer** [comment]
I have no way to test my Addon in the "Firefox Preview" App. Is it already possible to install Addons there?

**Comment by 532910** [comment]
It's possible, but as I know it's in nightlies only.

**Comment by M-Reimer** [comment]
So impossible for me to install easily. I'll continue development on what is called "Firefox for Android" until it is possible to try on "Firefox Preview".

**Comment by 532910** [comment]
Firefox for Android (fennec) developedment is discontinued.

**Comment by M-Reimer** [comment]
That's OK for me. If it gets to Android Apps then I'm end user only and for the end user "Firefox for Android" is still the way to go. I've installed the "Preview" version but uninstalled as soon as I've seen that there is no Addon support.

**Comment by 532910** [comment]
Addons are only in nightlies: https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly

**Comment by M-Reimer** [comment]
I've installed this now but can't get any addon to install. The XPI is just downloaded.

**Comment by 532910** [comment]
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

**Comment by M-Reimer** [comment]
I've already found that. In other words: Impossible for now.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by KrasnayaPloshchad** [comment]
Firefox for Android is now rebuild based on Fenix and rebranded as Firefox Daylight.

**Comment by M-Reimer** [comment]
And this browser is completely broken which, again, is a reason for not wasting time into Fenix for now.

I've suspended any Android testing for all of my Add-ons for now until Mozilla ships a browser with proper Add-on support. Happily I got forewarned so I could disable Play Store updates before my "full featured Firefox for Android" was "updated".

In my opinion Mozilla should give more respect to people trying to improve their product as a hobby in their spare time. Actually what I'm doing is unpaid work to make the Firefox browser more attractive for the users using my Add-ons. This "updated version" should never have been pushed as update to the "full-featured" Firefox for Android. It should have kept in Beta until developers, and not a few people at Mozilla, can decide whether they have tested their work to be compatible with the new version.

See also: https://github.com/mozilla-mobile/fenix/issues/14034

**Comment by 0xTyagi** [comment]
Working fine on Fenix and performance is also good.

**Comment by KrasnayaPloshchad** [comment]
Mozilla decided to give even more addon support for Daylight, so it’s possible to debug for what’s wrong on future versions of Firefox for Android.
https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/

**Comment by M-Reimer** [comment]
This actually is old news (02-09-2020) and so far there has been not much progress in this area.
The current state is still that I'm unable to test on Android since the crippled "update" was rolled out.

**Comment by yoasif** [comment]
This should be possible now: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

But I ran into an issue - https://github.com/mozilla/addons/issues/1252

EDIT: There is a workaround - you can add add-ons to a collection via the "Add to collection" box.

The add-on works for me.

**Comment by lfourquaux** [comment]
It looks like the workaround using collections does not work with the f-droid version of fenix (or at least, I didn't manage to make it work).

**Comment by M-Reimer** [comment]
The F-Droid version may be built with "Release" branding and not "Nightly". Then this feature will not be in there.

I'll test the new feature as soon as possible. This finally allows me to test my Add-ons and also use them for my own daily web browsing.

**Comment by KrasnayaPloshchad** [comment]
Yes it works for me when I install it on Nightly build, one problem is, while I open the option page in the add-on manager, the text looks so small.

**Comment by NuclearFej** [comment]
The add-on does not work for me in Nightly, Firefox attempts to navigate to `jar:file:///data/user/0/org.mozilla.fenix/files/mozilla/j256bczo.default/extensions/%7B7a4b4ee5-e5af-4a20-b179-d42ec510f3e8%7D.xpi!/content/web/viewer.html?file=<escaped URL>#pagemode=none` and returns the generic error page "Cannot Complete Request" "Additional information about this problem or error is currently unavailable." Is anyone else seeing this?

I'm willing to help debug, if that's possible.

Thank you for the add-on, by the way, it's been very nice to not have to jump out of Firefox to read PDFs.

**Comment by KrasnayaPloshchad** [comment]
Yes, I see.

**Comment by fxzjshm** [comment]
I have a 201201 version of Fenix Nightly, which works fine.  
I also had a 201225 version on another device, on which I encountered the same problem metioned above.  
But recently I upgraded it to 210111 version which also shows `jar:file:///data/user/0/org.mozilla.fenix/files/mozilla/2psf3uwz.default/extensions/%7B7a4b4ee5-e5af-4a20-b179-d42ec510f3e8%7D.xpi!/content/web/viewer.html?file=<url of the pdf>#pagemode=none` and "Cannot Complete Request", but if I click back button it navigates to something like `moz-extension://9df03e51-ef5a-4cd0-ae05-df2d50333f60/content/web/viewer.html?file=<url of the pdf>#pagemode=none` which displays the content correctly.  

UPDATE: On 210116 it seems that "Cannot Complete Request" disappears.

**Comment by NuclearFej** [comment]
@fxzjshm Thanks for posting, I am on 210115 now and the add-on just works, which is awesome!

**Comment by Gabriel85** [comment]
Yeah same problem on F-Droid stable, but works flawlessly on nightly! So I assume it will work again soon..
Would be great if this project could be revived! Although I have no idea how to debug it locally.. 🤔

**Comment by Kudou4869** [comment]
@M-Reimer  Firefox Android Support?

**Comment by M-Reimer** [comment]
@Kudou4869 I guess you have to ask Mozilla about this. They still have the same limitation in place that no author at all can actually produce Add-ons that install in the regular Android Firefox. The only browser which allows installing own Add-ons is Firefox Nightly. I currently have this installed in parallel to an old, outdated Android Firefox which still allows installing any Add-on you need.

My current plan is to get used to how Nightly behaves and works (I hate a few things about how they changed Firefox on Android and had to find workarounds and new workflows for a few things) and then completely uninstall the regular "Firefox for Android" for now.

I'm currently porting some of my Add-ons so they work well on Android (of course Nightly only). My collection is here:
https://addons.mozilla.org/de/firefox/collections/5149765/android/
At some point "android-pdf-js" will be on my list to be debugged and probably fixed/improved for "Fenix Nightly". Once this happens I'll close this Issue and point all future Issues to here. It's not my fault that Mozilla does bad decisions!

**Comment by M-Reimer** [comment]
Update is on its way. Hope this works without major issues...
