### ISSUE TITLE
Embed Hypothesis

### ISSUE THREAD

**Issue by nightscape** [M-Reimer/android-pdf-js#7]
Hi @M-Reimer, thanks for this extension!
What I'm trying to achieve with it is being able to annotate PDF files in Hypothesis.
I have a user script that loads Hypothesis in Firefox, but unfortunately that cannot be enabled on extension pages.
I'm wondering if it would be an option to add Hypothesis to this extension itself, possibly hidden behind a flag?
This should circumvent the user script problem and might hopefully be helpful to a few more people who want to do social highlighting on Android 😃

**Comment by M-Reimer** [comment]
Not in the current state of the Addon as "extension pages" have elevates privileges. I won't allow anything to load from an external server here. Even trying this could lead to my Add-on being blocked by Mozilla.

My goal for the future would be to change the way how PDF.js is loaded in a way that it virtually gets loaded from the server, hosting the PDF file, directly. This would mean that the actual PDF URL would be in the address bar and we no longer have an "extension page". But this most likely will not happen in the current "Firefox for Android" as the backend there has bugs that prevent this.
